"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "../providers/providers";
import "./globals.css";
import { loadGapiClient } from "./utils/gapi";
import { useEffect } from "react";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    loadGapiClient(process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!);
  }, []);
  
  return (
    <html lang="en">
      <body
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
